-- CREACIÓN DE BASE DE DATOS

CREATE DATABASE RECKITT
USE RECKITT

-- CREACIÓN DE TABLAS 

CREATE TABLE BRANDS (ID_BRAND INT NOT NULL IDENTITY, 
						BRAND VARCHAR (35),
						MANUFACTURER VARCHAR(35),
						PRIMARY KEY(ID_BRAND))

CREATE TABLE REGION (ID_REGION INT NOT NULL IDENTITY,
						REGION_NAME VARCHAR(25),
						PRIMARY KEY(ID_REGION))

CREATE TABLE SEGMENTS (ID_SEGMENT INT NOT NULL IDENTITY,
						SEGMENT_NAME VARCHAR(20),	
						PRIMARY KEY(ID_SEGMENT))


CREATE TABLE CATEGORY (ID_CATEGORY INT NOT NULL IDENTITY,
						CATEGORY VARCHAR (20),
						PRIMARY KEY(ID_CATEGORY))

CREATE TABLE SALES (ID_SALE	INT NOT NULL IDENTITY,
					ITEM_CODE VARCHAR(30),
					TOTAL_UNIT_SALES DECIMAL(10,3),	
					TOTAL_VALUE_SALES DECIMAL (10,3),
					SALE_DATE DATE,
					ID_REGION INT NOT NULL,
					FOREIGN KEY (ID_REGION) REFERENCES REGION(ID_REGION),
					PRIMARY KEY(ID_SALE))
					
					

CREATE TABLE FORMATS (ID_FORMAT INT NOT NULL IDENTITY,
					FORMAT_NAME VARCHAR(20),
					ATTR1 VARCHAR(30),
					ATTR2 VARCHAR(30),
					ATTR3 VARCHAR(30),
					ID_CATEGORY INT NOT NULL,
					ID_SEGMENT INT NOT NULL,
					FOREIGN KEY (ID_CATEGORY) REFERENCES CATEGORY(ID_CATEGORY),
					FOREIGN KEY (ID_SEGMENT) REFERENCES SEGMENTS(ID_SEGMENT),
					PRIMARY KEY(ID_FORMAT))

CREATE TABLE PRODUCTS (ITEM_CODE VARCHAR(30) NOT NULL,
						ITEM_DESCRIPTION VARCHAR(100),
						ID_BRAND INT NOT NULL,
						ID_CATEGORY INT NOT NULL,
						ID_FORMAT INT NOT NULL,
						FOREIGN KEY(ID_BRAND) REFERENCES BRANDS(ID_BRAND),
						FOREIGN KEY (ID_CATEGORY) REFERENCES CATEGORY(ID_CATEGORY),
						FOREIGN KEY (ID_FORMAT) REFERENCES FORMATS(ID_FORMAT),
						PRIMARY KEY (ITEM_CODE))

 --FINALIZA CREACIÓN DE TABLAS

--CONSULTAS A LA BASE DE DATOS

--Ventas por Categoría

Select B.BRAND AS MARCA, C.CATEGORY AS CATEGORÍA, 
	SUM(S.TOTAL_VALUE_SALES) TOTALVENTAS FROM PRODUCTS P 
	INNER JOIN SALES S ON S.ITEM_CODE=P.ITEM_CODE
	INNER JOIN CATEGORY C ON C.ID_CATEGORY=P.ID_CATEGORY
	INNER JOIN BRANDS B ON B.ID_BRAND=P.ID_BRAND
		GROUP BY B.BRAND, C.CATEGORY ORDER BY TOTALVENTAS DESC


--Ventas por Descripción del producto

	Select B.BRAND AS MARCA, P.ITEM_DESCRIPTION AS DESCRIPCIÓN, 
	SUM(S.TOTAL_VALUE_SALES) TOTALVENTAS FROM PRODUCTS P 
	INNER JOIN SALES S ON S.ITEM_CODE=P.ITEM_CODE
	INNER JOIN CATEGORY C ON C.ID_CATEGORY=P.ID_CATEGORY
	INNER JOIN BRANDS B ON B.ID_BRAND=P.ID_BRAND
		GROUP BY B.BRAND, P.ITEM_DESCRIPTION ORDER BY TOTALVENTAS DESC


--Ventas por Formato de producto

Select F.FORMAT_NAME AS FORMATO,
	SUM(S.TOTAL_VALUE_SALES) TOTALVENTAS FROM PRODUCTS P 
	INNER JOIN SALES S ON S.ITEM_CODE=P.ITEM_CODE
	INNER JOIN FORMATS F ON F.ID_FORMAT=P.ID_FORMAT
		GROUP BY F.FORMAT_NAME ORDER BY TOTALVENTAS DESC

	
--Ventas por Región

Select R.REGION_NAME AS REGIÓN, 
		SUM(S.TOTAL_VALUE_SALES) TOTALVENTAS FROM SALES S 
		INNER JOIN REGION R ON R.ID_REGION=S.ID_REGION GROUP BY R.REGION_NAME
			ORDER BY TOTALVENTAS DESC



--Ventas por Periodos de tiempo (Ventas por año)

SELECT DATEPART(YEAR, SALE_DATE) AÑO,  
		SUM(TOTAL_VALUE_SALES) TOTAL
		FROM SALES 
		GROUP BY DATEPART(YEAR, SALE_DATE)
			ORDER BY AÑO;



--(Ventas por mes)

SELECT DATEPART (YEAR, S.SALE_DATE) AÑO, 
		DATEPART(MONTH, S.SALE_DATE) MES,
		DATENAME (MONTH, S.SALE_DATE) NOMBRE, 
		SUM(S.TOTAL_VALUE_SALES) TOTALVENDIDO
		FROM SALES S
			GROUP BY DATEPART (YEAR, S.SALE_DATE), DATEPART(MONTH, S.SALE_DATE), DATENAME(MONTH, S.SALE_DATE)
			ORDER BY  AÑO, TOTALVENDIDO DESC

